### ISSUE TITLE
Gray page in option extension

### ISSUE THREAD

**Issue by TakeOwer** [pierrdu/lmdi_trashbin#2]
Hello, after installing the extension in the TAB "Board Trashbin -> Settings" I don't see any field/option but only a gray page!
My phpbb version is 3.3.13. I have other extensions installed v3.3.0 and they work!
Can you help me make it work?

Best Regards
Salvo

**Comment by pierrdu** [comment]
It looks like a corrupted file (maybe a language file?)

**Comment by TakeOwer** [comment]
> It looks like a corrupted file (maybe a language file?)
Hi,
I checked the language files, they seem to be correct!

**ENG**:

`if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge ($lang, array(
	'TRASHBIN'	=> 'Board Trashbin',
	'TRASHBIN_TEXT'	=> 'Topic moved by %s to the trashbin (source forum : %s).',

// ACP
	'ACP_TRASHBIN_TITLE'	=> 'Board Trashbin',
	'ACP_TRASHBIN_SETTINGS'	=> 'Settings',
	'ACP_TRASHBIN_ALLOW_FEATURE'		=> 'Target forum selection',
	'ACP_TRASHBIN_ALLOW_FEATURE_EXPLAIN'	=> 'You may select the forum used as a target of the topic move.',
	'ACP_TRASHBIN_FORUM_PRUNE_SETTINGS'		=> 'Trashbin prune settings',
	'ACP_TRASHBIN_FORUM_AUTO_PRUNE'			=> 'Enable auto-pruning',
	'ACP_TRASHBIN_FORUM_AUTO_PRUNE_EXPLAIN'	=> 'Topics placed in the trashbin are automatically pruned when the parameters (prune frequency and postage) below are satisfied.',
	'ACP_TRASHBIN_AUTO_PRUNE_DAYS'			=> 'Auto-prune post age',
	'ACP_TRASHBIN_AUTO_PRUNE_DAYS_EXPLAIN'	=> 'Number of days since last post after which topic is removed.',
	'ACP_TRASHBIN_AUTO_PRUNE_FREQ'			=> 'Auto-prune frequency',
	'ACP_TRASHBIN_AUTO_PRUNE_FREQ_EXPLAIN'	=> 'Time in days between pruning events.',

));`

**ITA**:

`if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge ($lang, array(
	'TRASHBIN'								=> 'Board Trashbin',
	'TRASHBIN_TEXT'							=> 'Argomento spostato da %s al cestino (dal forum : %s).',

// ACP
	'ACP_TRASHBIN_TITLE'					=> 'Board Trashbin',
	'ACP_TRASHBIN_SETTINGS'					=> 'Impostazioni',
	'ACP_TRASHBIN_ALLOW_FEATURE'			=> 'Seleziona il forum di destinazione (che farà da Cestino)',
	'ACP_TRASHBIN_ALLOW_FEATURE_EXPLAIN'	=> 'È possibile selezionare il forum utilizzato, come obiettivo dello spostamento dell’argomento.',
	'ACP_TRASHBIN_FORUM_PRUNE_SETTINGS'		=> 'Impostazioni Prune del cestino',
	'ACP_TRASHBIN_FORUM_AUTO_PRUNE'			=> 'Abilita cancellazione automatica',
	'ACP_TRASHBIN_FORUM_AUTO_PRUNE_EXPLAIN'	=> 'Gli argomenti inseriti nel cestino vengono sfoltiti automaticamente quando i parametri (frequenza del Prune e/o pubblicazione) riportati di seguito sono soddisfatti.',
	'ACP_TRASHBIN_AUTO_PRUNE_DAYS'			=> 'Giorni prima dell’Auto-prune',
	'ACP_TRASHBIN_AUTO_PRUNE_DAYS_EXPLAIN'	=> 'Numero di giorni dall’ultimo messaggio dopo i quali l’argomento verrà rimosso.',
	'ACP_TRASHBIN_AUTO_PRUNE_FREQ'			=> 'Frequenza cancellazione automatica dei messaggi',
	'ACP_TRASHBIN_AUTO_PRUNE_FREQ_EXPLAIN'	=> 'Tempo fra i vari processi di cancellazione espresso in giorni.',

));`
I tried to uninstall and reinstall the extension, purged the cache and also cleaned up the "twig" folder, but nothing change.
This extension interests me a lot, can you help me to solve? Thanks in advance whatever the answer 😊
Regards
Salvo

**Comment by pierrdu** [comment]
I thought that the blank page was an error 500, most of the time a problem with quotes in a language file. You have the same problem with the English file?

**Comment by TakeOwer** [comment]
> I thought that the blank page was an error 500, most of the time a problem with quotes in a language file. You have the same problem with the English file?

Also tried with the English language only. Nothing changes, I always see the gray screen!
![gray_screen](https://github.com/user-attachments/assets/bf32c154-dde9-4313-b240-29ea93a08d05)

Regards

**Comment by pierrdu** [comment]
It's looks like an error 500. Can you access the server error log?

**Comment by Skouat** [comment]
@TakeOwer use the following version: https://github.com/phpbb-fr-com/lmdi_trashbin/releases/tag/1.3.3

@pierrdu I will contact you via PM

**Comment by Skouat** [comment]
@TakeOwer Make sur your language file use "UTF-8 without BOM" and also use "Unix" format.
To avoid these issue, copy the file from `fr` or `de` language (not the `en`) and paste it in your `it` folder.
Then, even if it's not your language check that the extension works.

If this is the cas, you can start (re)translating in Italian ;)

**Comment by TakeOwer** [comment]
> @TakeOwer Make sur your language file use "UTF-8 without BOM" and also use "Unix" format. To avoid these issue, copy the file from `fr` or `de` language (not the `en`) and paste it in your `it` folder. Then, even if it's not your language check that the extension works.
> 
> If this is the cas, you can start (re)translating in Italian ;)

Good morning Skouat,
I tried with French language, German language and English languiage. In the ACP extension settings, I am always shown a gray page 😒
I think the problem is in the "trashbin_module.php" module of the extension.

**Comment by TakeOwer** [comment]
Hello again,
I think I found the mistake. In fact, when I disable this piece of code, the settings page is displayed correctly.
`$sql = 'SELECT * FROM ' . FORUMS_TABLE . '
			WHERE forum_id = ' . (int) $target;
		$result = $db->sql_query($sql);
		$forum = $db->sql_fetchrow ($result);
		$template->assign_vars (array(
			'C_ACTION'		=> $action_config,
			'S_PRUNE_ENABLE'	=> $forum['enable_prune'],
			'PRUNE_DAYS'		=> $forum['prune_days'],
			'PRUNE_FREQ'		=> $forum['prune_freq'],
			));
		$db->sql_freeresult($result);`
I understand php but not extensions (although they are based on php) can someone give me some help?
Thank you whatever the outcome
Salvo

**Comment by pierrdu** [comment]
If you delete this piece of code, you can't define the settings for the selected forum anymore.
If you run the extension without it, what is displayed? Only a list of forums of your board?

**Comment by TakeOwer** [comment]
> If you delete this piece of code, you can't define the settings for the selected forum anymore.
> If you run the extension without it, what is displayed? Only a list of forums of your board?

If I disabling this piece of code displays this page
![trashbin_ext](https://github.com/user-attachments/assets/40bfd3c9-7480-4fbb-b231-9c1168d328bf)

Obviously if I select the forum that will act as a trash or any other setting is not saved in the DB.
Salvo

**UPDATE:**
I finally solved it. The change to be made is in the "acp_trashbin_body.html" file.
To make it work, this must be added `id="enable_prune"` 😂

`	<dd><label><input type="radio" id="enable_prune" class="radio" name="enable_prune" value="1"{% if S_PRUNE_ENABLE %} id="enable_prune" checked="checked"{% endif %} /> {{ lang('YES') }}</label>
		<label><input type="radio" id="enable_prune" class="radio" name="enable_prune" value="0"{% if not S_PRUNE_ENABLE %} id="enable_prune" checked="checked"{% endif %} /> {{ lang('NO') }}</label></dd>`

Regards
Salvo

**Comment by pierrdu** [comment]
There must be something special in your board, because this doesn't make sense for me.

**Comment by TakeOwer** [comment]
> There must be something special in your board, because this doesn't make sense for me.

In fact, it doesn't make sense to me either. But once this change is made, everything works correctly 😊
Thanks anyway for the support

Regards
Salvo

**Comment by Skouat** [comment]
> Hello again, I think I found the mistake. In fact, when I disable this piece of code, the settings page is displayed correctly.
```
		$sql = 'SELECT * FROM ' . FORUMS_TABLE . '
			WHERE forum_id = ' . (int) $target;
		$result = $db->sql_query($sql);
		$forum = $db->sql_fetchrow ($result);
		$template->assign_vars (array(
			'C_ACTION'		=> $action_config,
			'S_PRUNE_ENABLE'	=> $forum['enable_prune'],
			'PRUNE_DAYS'		=> $forum['prune_days'],
			'PRUNE_FREQ'		=> $forum['prune_freq'],
			));
		$db->sql_freeresult($result);
```
>I understand php but not extensions (although they are based on php) can someone give me some help? Thank you whatever the outcome Salvo

For this issue, you just have to surround the [code](https://github.com/pierrdu/lmdi_trashbin/blob/master/acp/trashbin_module.php#L79-L89) with an `if` condition on the `$target` variable

```
		if ($target)
		{
		// orignal code
		}
```



> I finally solved it. The change to be made is in the "acp_trashbin_body.html" file. To make it work, this must be added `id="enable_prune"` 😂
> 
```
<dd><label><input type="radio" id="enable_prune" class="radio" name="enable_prune" value="1"{% if S_PRUNE_ENABLE %} id="enable_prune" checked="checked"{% endif %} /> {{ lang('YES') }}</label> <label><input type="radio" id="enable_prune" class="radio" name="enable_prune" value="0"{% if not S_PRUNE_ENABLE %} id="enable_prune" checked="checked"{% endif %} /> {{ lang('NO') }}</label></dd>
```
Please undo this change, the `id="enable_prune"` is already declared just after `{% if S_PRUNE_ENABLE %}` and `{% if not S_PRUNE_ENABLE %}`

**Comment by pierrdu** [comment]
Very good idea. Thanks Skouat.
